# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'CoordinatorExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoordinatorExample
	pod 'Lepaya-Coordinator'
end
